%% generate_CLIK_model.m
%  Builds LBR_MED_CLIK.slx — Closed Loop Inverse Kinematics Simulink model.
%
%  CLIK LAW (class slides 69-70):
%    q_dot = J_pinv(q) * [p_dot_d + Kp*(p_d - p_e(q));
%                         w_d    + Ko*e_O            ]
%           + (I - J_pinv*J) * q_dot0
%
%  where:
%    J_pinv = J^T * (J*J^T)^{-1}   (right pseudo-inverse, 7x6)
%    e_O    = r * theta,  R(theta,r) = R_d * R_e^T  (orientation error)
%    (I-J_pinv*J)*q_dot0 = null-space term for redundancy stabilisation
%    q_dot0 = -k0*(q - q_mid)  (joint centering potential)
%
%  Block layout:
%    [Constant p_d, R_d]  --->  [CLIK Function]  ---> [Integrator] -> q
%    [Zero w_d, p_dot_d]           ^                        |
%                                  |                        v
%                               [DK block]  <--------------+
%
%  Run generate_LBR_MED.m and generate_Jacobian_model.m first.

addpath(fullfile(fileparts(mfilename('fullpath')), '..', ...
    'Robotics_Symbolic_Matlab_Toolbox-2'));

mdl     = 'LBR_MED_CLIK';
libName = 'LBR_MED_Lib';

if ~exist([libName '.slx'],'file')
    error('Run generate_LBR_MED.m and generate_Jacobian_model.m first.');
end

if bdIsLoaded(mdl), close_system(mdl,0); end
new_system(mdl);
open_system(mdl);
load_system(libName);

%% Gain parameters (edit here to tune)
Kp  = 2.0;   % position gain
Ko  = 2.0;   % orientation gain
k0  = 0.5;   % null-space joint-centering gain

% Joint limits center (rad) — approximate midpoints
q_mid = [0; 0; 0; 0; 0; 0; 0];

%% MATLAB Function block: CLIK law
clikSrc = sprintf([ ...
'function q_dot = CLIK(q, p_d, R_d_flat)\n' ...
'%% CLIK law for KUKA LBR MED 7 R800\n' ...
'Kp  = %g * eye(3);\n' ...
'Ko  = %g * eye(3);\n' ...
'k0  = %g;\n' ...
'q_mid = [%s]'';\n' ...
'\n' ...
'%% DK\n' ...
'[R_e, p_e] = LBR_MED_Direct_Kinematics(q(1),q(2),q(3),q(4),q(5),q(6),q(7));\n' ...
'\n' ...
'%% Jacobian\n' ...
'J = LBR_MED_Jacobian(q(1),q(2),q(3),q(4),q(5),q(6),q(7));\n' ...
'\n' ...
'%% Pseudo-inverse\n' ...
'JJT = J*J'';\n' ...
'J_pinv = J'' / (JJT + 1e-6*eye(6));  %% damped\n' ...
'\n' ...
'%% Position error\n' ...
'e_p = p_d - p_e;\n' ...
'\n' ...
'%% Orientation error (angle-axis from R_d*R_e'')\n' ...
'R_d = reshape(R_d_flat,3,3);\n' ...
'Re  = R_d * R_e'';\n' ...
'theta = acos(min(1,max(-1,(trace(Re)-1)/2)));\n' ...
'if abs(theta) < 1e-8\n' ...
'    e_O = zeros(3,1);\n' ...
'else\n' ...
'    r = [Re(3,2)-Re(2,3); Re(1,3)-Re(3,1); Re(2,1)-Re(1,2)]/(2*sin(theta));\n' ...
'    e_O = r * theta;\n' ...
'end\n' ...
'\n' ...
'%% Task velocity\n' ...
'v = [Kp*e_p; Ko*e_O];\n' ...
'\n' ...
'%% Null-space term (joint centering)\n' ...
'q_dot0 = -k0*(q - q_mid);\n' ...
'N = eye(7) - J_pinv*J;\n' ...
'\n' ...
'q_dot = J_pinv*v + N*q_dot0;\n' ...
'end\n'], Kp, Ko, k0, num2str(q_mid(:)', '%.4f '));

% Write CLIK function to file so Simulink can see it
fid = fopen(fullfile(fileparts(mfilename('fullpath')), 'CLIK_law.m'), 'w');
fprintf(fid, '%s', clikSrc);
fclose(fid);

%% Target (constant desired pose)
% Default: arm straight up at home
p_d_val = [0; 0; 1.266];
R_d_val = eye(3);

%% Add blocks
x0=50; dy=80;

% Desired position constant
add_block('simulink/Sources/Constant', [mdl '/p_d'], ...
    'Value', mat2str(p_d_val), 'Position', [x0,50,x0+100,90]);

% Desired rotation constant (flattened 9-vector)
add_block('simulink/Sources/Constant', [mdl '/R_d'], ...
    'Value', mat2str(R_d_val(:)'), 'Position', [x0,110,x0+100,150]);

% Initial joint angles
add_block('simulink/Sources/Constant', [mdl '/q0'], ...
    'Value', '[0.1;0.1;0;0.1;0;0.1;0]', 'Position', [x0,170,x0+100,210]);

% Integrator (7 states = q)
add_block('simulink/Continuous/Integrator', [mdl '/Integrator'], ...
    'InitialCondition', '[0.1;0.1;0;0.1;0;0.1;0]', ...
    'Position', [500,120,560,160]);

% MATLAB Function block for CLIK
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [mdl '/CLIK'], 'Position', [300,80,480,200]);

% To Workspace for q
add_block('simulink/Sinks/To Workspace', [mdl '/q_out'], ...
    'VariableName', 'q_out', 'Position', [620,120,720,160]);

% Scope
add_block('simulink/Sinks/Scope', [mdl '/Scope'], ...
    'Position', [620,60,680,100]);

%% Connections
add_line(mdl, 'Integrator/1', 'CLIK/1', 'autorouting','on');
add_line(mdl, 'p_d/1',        'CLIK/2', 'autorouting','on');
add_line(mdl, 'R_d/1',        'CLIK/3', 'autorouting','on');
add_line(mdl, 'CLIK/1',       'Integrator/1', 'autorouting','on');
add_line(mdl, 'Integrator/1', 'q_out/1',  'autorouting','on');
add_line(mdl, 'CLIK/1',       'Scope/1',  'autorouting','on');

%% Simulation settings
set_param(mdl, 'StopTime', '10', 'Solver', 'ode45');

save_system(mdl);
fprintf('CLIK model saved as %s.slx\n', mdl);
fprintf('Open it in Simulink and run (Ctrl+T) to simulate convergence.\n');
